#!/bin/sh
# Handle git-diff headers upon adding an empty file.

. "${srcdir=.}/init.sh"; path_prepend_ ..
print_ver_ vc-dwim

require_git_

fail=0

cat <<EOF > ChangeLog || framework_failure_
2006-09-04  Jim Meyering  <jim@meyering.net>
EOF
git init > /dev/null			\
  && echo foo > x			\
  && git add .				\
  && git commit -m m . > /dev/null	\
  && git mv x y				\
  && : > y				\
    || framework_failure_

cat <<EOF >> ChangeLog || framework_failure_

	summary
	* x: Rename to...
	* y: ...this.
EOF

cat <<\EOF > exp || framework_failure_
summary
* x: Rename to...
* y: ...this.
diff --git a/x b/x
deleted file mode 100644
index 257cc56..0000000
--- a/x
+++ /dev/null
@@ -1 +0,0 @@
-foo
diff --git a/y b/y
new file mode 100644
index 0000000..e69de29
EOF

vc-dwim ChangeLog > out || fail=1
compare exp out || fail=1

Exit 0
