#!/bin/sh
# Exercise the --author='user name <email@addr.dom>' option.

if test "$VERBOSE" = yes; then
  set -x
  vc-dwim --version
fi

. $srcdir/require-git
. $srcdir/trap-setup

framework_failure=0
mkdir -p $tmp && cd $tmp \
  || framework_failure=1

cat <<EOF > ChangeLog || framework_failure=1
2006-09-04  Jim Meyering  <jim@meyering.net>
EOF
git init-db > /dev/null 2>&1		\
  && git add .				\
  && git commit -m m . > /dev/null 2>&1	\
    || framework_failure=1

touch x || framework_failure=1
git add x || framework_failure=1
cat <<EOF >> ChangeLog || framework_failure=1

	* x: whatever...
EOF

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

set -e

name_and_addr='joe blow <j@blow.org>'
vc-dwim --commit --author="$name_and_addr" > /dev/null
git-log --max-count=1 > out
grep "^Author: $name_and_addr" out > /dev/null

exit 0
