#!/bin/sh
# Exercise git-mv's renaming.  Results in different diff syntax.
# This also exercises the other fix: handle a diff header line
# with only one comma, e.g., "@@ -1 +1,4 @@".

if test "$VERBOSE" = yes; then
  set -x
  vc-dwim --version
fi

. $srcdir/require-git
. $srcdir/trap-setup

framework_failure=0
mkdir -p $tmp && cd $tmp \
  || framework_failure=1

cat <<EOF > ChangeLog || framework_failure=1
2006-09-04  Jim Meyering  <jim@meyering.net>
EOF
git init-db 2> /dev/null		\
  && touch x				\
  && git add .				\
  && git commit -m m . 2> /dev/null	\
  && git mv x y				\
    || framework_failure=1

cat <<EOF >> ChangeLog || framework_failure=1

	* x: Rename to...
	* y: ...this.
EOF

cat <<\EOF > exp || framework_failure=1
* x: Rename to...
* y: ...this.
diff --git a/x b/y
similarity index 100%
rename from x
rename to y
EOF

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

set -e

# Ensure that we get the "rename from..." and "rename to..."
# lines in diff output.
vc-dwim --diff x y > out
grep -v '^*' exp > e1
cmp out e1 \
  || { diff out e1 2> /dev/null; false; }

rm -f out
vc-dwim ChangeLog > out

cmp out exp \
  || { diff out exp 2> /dev/null; false; }

exit 0
