#!/bin/sh
# ensure that vc-dwim inserts a blank line when necessary

if test "$VERBOSE" = yes; then
  set -x
  vc-dwim --version
fi

. $srcdir/require-git
. $srcdir/trap-setup

framework_failure=0
mkdir -p $tmp && cd $tmp \
  || framework_failure=1

cat <<EOF > ChangeLog || framework_failure=1
2006-09-04  Jim Meyering  <jim@meyering.net>
EOF
git init > /dev/null 2>&1		\
  && git add .				\
  && git commit -m m . > /dev/null 2>&1	\
    || framework_failure=1

touch x || framework_failure=1
git add x || framework_failure=1
cat <<EOF >> ChangeLog || framework_failure=1

	Summary
	* x: body
EOF
cat <<EOF >> exp || framework_failure=1
    Summary

    * x: body
EOF

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

set -e
fail=0

vc-dwim --commit > /dev/null
git log -1 > out.t
tail -n3 out.t |sed 's/^    $//' > out
diff -u out exp || fail=1
exit 0
