#!/bin/sh
# Test the (first?) fix of 2006-09-04.

if test "$VERBOSE" = yes; then
  set -x
  vc-dwim --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

touch f ChangeLog || framework_failure=1
git init-db 2> /dev/null || framework_failure=1
git add f ChangeLog || framework_failure=1
git commit -m m . 2> /dev/null || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

cat <<EOF > ChangeLog || fail=1
2006-09-04  Jim Meyering  <jim@meyering.net>

	Summary...
	* f: X.
	(dog): bark.
EOF
echo bow > f || fail=1

vc-dwim ChangeLog > out || fail=1

# FIXME: The "* f: " prefix doesn't belong on the "Summary..." line.
cat <<\EOF > exp || fail=1
* f: Summary...
* f: X.
(dog): bark.
diff --git a/f b/f
index e69de29..de03f25 100644
--- a/f
+++ b/f
@@ -0,0 +1 @@
+bow
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
