#!/bin/sh
# Test the second fix of 2006-09-04.

. "${srcdir=.}/init.sh"; path_prepend_ ..
print_ver_ vc-dwim

require_git_

touch f || framework_failure_
cat <<EOF > ChangeLog || framework_failure_
2006-09-04  Jim Meyering  <jim@meyering.net>

	* f: X.
EOF
git init > /dev/null || framework_failure_
git add . || framework_failure_
git commit -m m . > /dev/null || framework_failure_

fail=0

cat <<EOF >> ChangeLog || fail=1
	(dog): bark.
EOF
echo bow >> f || fail=1

vc-dwim ChangeLog > out || fail=1

cat <<\EOF > exp || fail=1
* f (dog): bark.
diff --git a/f b/f
index e69de29..de03f25 100644
--- a/f
+++ b/f
@@ -0,0 +1 @@
+bow
EOF

compare exp out || fail=1

Exit $fail
