#!/bin/sh
# Test the second fix of 2006-09-04.

if test "$VERBOSE" = yes; then
  set -x
  vc-dwim --version
fi

. $srcdir/trap-setup

require_git_

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

touch f || framework_failure=1
cat <<EOF > ChangeLog || framework_failure=1
2006-09-04  Jim Meyering  <jim@meyering.net>

	* f: X.
EOF
git init > /dev/null || framework_failure=1
git add . || framework_failure=1
git commit -m m . > /dev/null || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

cat <<EOF >> ChangeLog || fail=1
	(dog): bark.
EOF
echo bow >> f || fail=1

vc-dwim ChangeLog > out || fail=1

cat <<\EOF > exp || fail=1
* f (dog): bark.
diff --git a/f b/f
index e69de29..de03f25 100644
--- a/f
+++ b/f
@@ -0,0 +1 @@
+bow
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

Exit $fail
