#!/bin/sh
# Fail when ChangeLog is not version controlled.

# Disable for now.
# Need support for detecting when a file is version-controlled
# to do this properly.
exit 0

if test "$VERBOSE" = yes; then
  set -x
  vc-dwim --version
fi

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'stat=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $stat' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

touch ChangeLog || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

vc-dwim ChangeLog > out 2>&1 || fail=1

cat <<\EOF > exp || fail=1
FIXME
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
