#!/bin/sh
# Fail when ChangeLog is not version controlled.

# Disable for now.
# Need support for detecting when a file is version-controlled
# to do this properly.
exit 0

. "${srcdir=.}/init.sh"; path_prepend_ ..
print_ver_ vc-dwim

touch ChangeLog || framework_failure_

fail=0

vc-dwim ChangeLog > out 2>&1 || fail=1

cat <<\EOF > exp || fail=1
FIXME
EOF

compare exp out || fail=1

Exit $fail
