#!/bin/sh
# Given a 3-level git tree with the working directory in the middle directory,
# and vc-dwim operating on a ChangeLog in the lowest level directory.

. "${srcdir=.}/init.sh"; path_prepend_ ..
print_ver_ vc-dwim

require_git_

ChangeLog=2/3/ChangeLog
mkdir -p 2/3		|| framework_failure_
touch 2/3/f $ChangeLog	|| framework_failure_
git init > /dev/null	|| framework_failure_
git add .		|| framework_failure_
git commit -m m . > /dev/null || framework_failure_

cat <<EOF > $ChangeLog || framework_failure_
2006-09-04  Jim Meyering  <jim@meyering.net>

	1-line summary
	* f: X.
EOF
echo z > 2/3/f || framework_failure_

fail=0
cd 2

vc-dwim 3/ChangeLog > out 2>err || fail=1

cat <<\EOF > exp || fail=1
1-line summary
* f: X.
diff --git a/2/3/f b/2/3/f
index e69de29..b680253 100644
--- a/2/3/f
+++ b/2/3/f
@@ -0,0 +1 @@
+z
EOF

compare exp out || fail=1

Exit $fail
