#!/bin/sh
# Demonstrate that using a ChangeLog in a subdir works from that subdir,
# when using git.  See the diff_outputs_full_file_names method for why
# this is different.  It's easy when run from the top level.

. "${srcdir=.}/init.sh"; path_prepend_ ..
print_ver_ vc-dwim

require_git_

mkdir s || framework_failure_
touch s/f s/ChangeLog || framework_failure_
git init > /dev/null || framework_failure_
git add . || framework_failure_
git commit -m m . > /dev/null || framework_failure_

fail=0

cat <<EOF > s/ChangeLog || fail=1
2006-09-04  Jim Meyering  <jim@meyering.net>

	1-line summary
	* f: X.
EOF
echo bow > s/f || fail=1
cd s

vc-dwim ChangeLog > out 2>err || fail=1

cat <<\EOF > exp || fail=1
1-line summary
* f: X.
diff --git a/s/f b/s/f
index e69de29..de03f25 100644
--- a/s/f
+++ b/s/f
@@ -0,0 +1 @@
+bow
EOF

compare exp out || fail=1
test $fail = 1 && diff exp out 2> /dev/null

Exit $fail
