#!/bin/sh
# Test the symlinked ChangeLog feature.

if test "$VERBOSE" = yes; then
  set -x
  vc-dwim --version
fi

. $srcdir/require-hg
. $srcdir/require-git

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd $pwd; chmod -R u+rwx $t0; rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

mkdir d m || framework_failure=1
touch m/f || framework_failure=1
cat <<EOF > d/ChangeLog || framework_failure=1
2006-09-04  Jim Meyering  <jim@meyering.net>

EOF
(cd m && hg init 2> /dev/null)            || framework_failure=1
(cd m && hg add . ) > /dev/null 2>&1      || framework_failure=1
(cd m && hg ci -m m . ) > /dev/null 2>&1  || framework_failure=1
ln -s ../d/ChangeLog m
echo a >> m/f

(cd d && git init-db 2> /dev/null)        || framework_failure=1
(cd d && git add . 2> /dev/null)          || framework_failure=1
(cd d && git commit -m m . ) 2> /dev/null || framework_failure=1
cat <<EOF >> d/ChangeLog || framework_failure=1
	* f: X.
EOF

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

(cd m && vc-dwim ChangeLog) > out || fail=1

cut -b1-7 out > k; mv k out
cat <<\EOF > exp || fail=1
* f: X.
diff -r
--- a/f
+++ b/f
@@ -0,0
+a
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(cd m && vc-dwim --commit ChangeLog) > out || fail=1

cut -b1-7 out > k; mv k out
cat <<\EOF > exp || fail=1
* f: X.
diff -r
--- a/f
+++ b/f
@@ -0,0
+a
M Chang
Committ
f
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
