#!/bin/sh
# Ensure that a two-line ChangeLog attribution is accepted.

. "${srcdir=.}/init.sh"; path_prepend_ ..
print_ver_ vc-dwim

require_git_

touch f ChangeLog || framework_failure_
git init > /dev/null || framework_failure_
git add . || framework_failure_
git commit -m m . > /dev/null || framework_failure_

fail=0

cat <<EOF > ChangeLog || fail=1
2006-09-04  Jim Meyering  <jim@meyering.net>
	and Somebody Else <se@example.com>

	* f: X.
EOF
echo bow > f || fail=1

vc-dwim ChangeLog > out || fail=1

cat <<\EOF > exp || fail=1
* f: X.
diff --git a/f b/f
index e69de29..de03f25 100644
--- a/f
+++ b/f
@@ -0,0 +1 @@
+bow
EOF

compare exp out || fail=1

Exit $fail
