#!/bin/sh
# Fail if two ChangeLog files use different version control systems.

if test "$VERBOSE" = yes; then
  set -x
  vc-dwim --version
fi

. $srcdir/require-git
. $srcdir/require-hg
. $srcdir/trap-setup

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

mkdir m g || framework_failure=1
touch m/f g/f || framework_failure=1
cat <<EOF > g/ChangeLog || framework_failure=1
2006-09-04  Jim Meyering  <jim@meyering.net>

	* f: X.
EOF
cp g/ChangeLog m || framework_failure=1
(cd m && hg init 2> /dev/null)            || framework_failure=1
(cd m && hg add . ) > /dev/null 2>&1      || framework_failure=1
(cd m && hg ci -m m . ) > /dev/null 2>&1  || framework_failure=1

(cd g && git init-db 2> /dev/null)        || framework_failure=1
(cd g && git add . 2> /dev/null)          || framework_failure=1
(cd g && git commit -m m . ) 2> /dev/null || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0

vc-dwim g/ChangeLog m/ChangeLog 2> out && fail=1

cat <<\EOF > exp || fail=1
vc-dwim: ChangeLog files are managed by more than one version-control system:
  g/ChangeLog: git
  m/ChangeLog: hg
EOF

cmp out exp || fail=1
test $fail = 1 && diff out exp 2> /dev/null

(exit $fail); exit $fail
